dataset_name: ped2
device: cuda:0
mean: [0.00049519236, 0.034649044, 0.012760395]
std: [0.00030447403, 0.010666361, 0.004660762]
train_dataset_dir: ./data/ped2/train/
test_dataset_dir: ./data/ped2/test/
gt_dir: ./data/ped2/ped2_gt.json
train_box_dir: ./data/ped2/ped2_train.npy
test_box_dir: ./data/ped2/ped2_test.npy
teacher_name: resnet
teacher_dir: ./teacher/resnet50-0676ba61.pth
k: 2
max_epoch: 80
num_obj: 3
hybird_para: [0.01,  0.65, 0.35]
task: pred
max_epoch: 120
milestone: 60
lr_decay: 0.8
learning_rate: 0.0001
save_dir: ./model/ped2_pred_student.pt
batch_size: 128
loss_para: {gen: 0.8, grad: 0.1, fea: 0.2}